function join(arr1: string[], arr2: string[]) {
    return arr1.map((str1) => arr2.map((str2) => `${str1}${str2}`)).flat();
}

export const SOMMERJOBB_KEYWORDS: readonly string[] = Object.freeze([
    ...join(
        ["sommer", "sommar", "sumar"],
        ["hjelp", "jobb", "oppdrag", "sesong", "vikar", "vikarar", "vikarer", "vikariat"],
    ),
    ...join(["ferie"], ["jobb", "vikar", "vikarar", "vikarer", "vikariat"]),
    ...join(["sesong"], ["hjelp", "jobb", "vikar", "vikarar", "vikarer", "vikariat"]),
    "summer",
]);

export const SOMMERJOBB_CATEGORIES = Object.freeze(
    [
        {
            label: "Butikk",
            values: [
                "bensinstasjon",
                "butikk",
                "butikkarbeid",
                "butikkarbeider",
                "butikkmedarbeider",
                "butikkselger",
                "detaljhandel",
                "kiosk",
                "varepåfylling",
            ],
        },
        {
            label: "Helse og omsorg",
            values: [
                "aktivitetsleder",
                "ambulanse",
                "apotek",
                "apotektekniker",
                "avlastningssenter",
                "barnehage",
                "barnehageassistent",
                "bpa",
                "eldreomsorg",
                "ergoterapeut",
                "farmasi",
                "farmasøyt",
                "fysioterapeut",
                "heimeteneste",
                "helse",
                "helsearbeid",
                "helsearbeider",
                "helsefag",
                "helsefagarbeider",
                "helsehjelp",
                "helsesekretær",
                "hjemmehjelp",
                "hjemmetjeneste",
                "hjemmetjenesten",
                "lege",
                "legesenter",
                "medisinstudent",
                "miljøarbeid",
                "miljøarbeider",
                "miljøterapeut",
                "miljøterapi",
                "omsorg",
                "omsorgsarbeid",
                "omsorgsbolig",
                "omsorgsbustad",
                "omsorgssenter",
                "reiseassistanse",
                "sfo",
                "sjukehus",
                "skole",
                "sykehjem",
                "sykehus",
                "sykehusapotek",
                "sykepleier",
                "sykepleierstudent",
                "tannhelse",
                "tannklinikk",
                "tannpleier",
                "voksenopplæring",
            ],
        },
        {
            label: "Salg og service",
            values: [
                "bibliotek",
                "billettering",
                "billettkontroll",
                "bilutleie",
                "booking",
                "feltsalg",
                "feltverver",
                "fundraiser",
                "innsjekk",
                "innsjekking",
                "kundebehandler",
                "kundekonsulent",
                "kundesenter",
                "ordrebehandling",
                "passasjerservice",
                "resepsjon",
                "resepsjonist",
                "servicearbeid",
                "servicemedarbeider",
                "support",
                "telefonarbeid",
                "vakthold",
                "vekter",
                "vervearbeid",
                "verver",
                "retail",
                "dørsalg",
            ],
        },
        {
            label: "Praktisk arbeid",
            values: [
                "anlegg",
                "anleggsarbeid",
                "arkivering",
                "bilverksted",
                "dekkbytte",
                "dekkhotell",
                "dekkmontering",
                "dekkomlegging",
                "digitalisering",
                "drift",
                "fabrikk",
                "ferge",
                "flyarbeider",
                "flyarbeider",
                "flytting",
                "gartner",
                "gjenvinning",
                "gjenvinningsstasjon",
                "gravplass",
                "gressklipping",
                "grøntanlegg",
                "grøntareal",
                "gårdsarbeid",
                "havbruk",
                "industri",
                "industriarbeider",
                "industrimekanikk",
                "kirkegård",
                "kontorbeplantning",
                "lager",
                "lagerarbeid",
                "lageroperatør",
                "landbruk",
                "lasting",
                "miljøstasjon",
                "park",
                "parkanlegg",
                "parkarbeid",
                "parkarbeider",
                "parvedlikehold",
                "plenklipping",
                "posthåndtering",
                "produksjon",
                "produksjonsarbeider",
                "produksjonsmedarbeider",
                "produktutvikling",
                "renovasjon",
                "reparasjon",
                "restaurering",
                "skog",
                "skogbruk",
                "terminalkoordinator",
                "utearbeid",
                "vaktmester",
                "vedlikehold",
                "verksted",
                "dataregistrering",
            ],
        },
        {
            label: "Renhold",
            values: [
                "housekeeper",
                "reinhald",
                "reinhold",
                "rengjøring",
                "renhold",
                "renholder",
                "renholdsarbeider",
                "renholdsmedarbeider",
                "vaskehjelp",
            ],
        },
        {
            label: "Restaurant og kafé",
            values: [
                "baker",
                "bakeri",
                "barista",
                "bartender",
                "cafe",
                "café",
                "foodtruck",
                "kafe",
                "kaffebar",
                "kafé",
                "kafémedarbeider",
                "kantine",
                "kjøkken",
                "kjøkkenassistent",
                "kjøkkenhjelp",
                "kjøkkenpersonell",
                "kokk",
                "pub",
                "restaurant",
                "ryddehjelp",
                "servering",
                "servitør",
                "storkjøkken",
            ],
        },
        {
            label: "Sjåfør",
            values: ["avislevering", "isbil", "pakkelevering", "lastebilsjåfør", "sjåfør"],
        },
        {
            label: "Turisme",
            values: [
                "camping",
                "guide",
                "guiding",
                "museum",
                "reiseliv",
                "turguide",
                "turisme",
                "turistinformasjon",
                "turistvert",
                "vitensenter",
            ],
        },
        {
            label: "Andre",
            values: [
                "administrasjon",
                "analytiker",
                "arbeidsinkludering",
                "arealplanlegging",
                "brannvesen",
                "byutvikling",
                "dataingeniør",
                "design",
                "eiendomsskatt",
                "fengsel",
                "fengselsbetjent",
                "forsker",
                "forskingsteknikar",
                "hr",
                "ingeniør",
                "kartdata",
                "kartproduksjon",
                "kartverk",
                "konsulent",
                "kraftnett",
                "politi",
                "politibetjent",
                "programmerer",
                "programmering",
                "prosjektmedarbeider",
                "rådgivning",
                "saksbehandler",
                "saksbehandling",
                "sekretær",
                "skipsdesign",
                "strandsonekartlegger",
                "sykkelpatrulje",
                "systemingeniør",
                "systemutvikling",
                "teknologi",
                "utvikler",
                "økonomisjef",
                "diplom-is",
                "ungdomsjobb",
            ],
        },
    ].map((row) => Object.freeze({ label: row.label, values: Object.freeze(row.values) })),
);
