function join(arr1: string[], arr2: string[]) {
    return arr1.map((str1) => arr2.map((str2) => `${str1}${str2}`)).flat();
}

export const SOMMERJOBB_KEYWORDS: readonly string[] = Object.freeze([
    ...join(
        ["sommer", "sommar", "sumar"],
        ["hjelp", "jobb", "oppdrag", "sesong", "vikar", "vikarar", "vikarer", "vikariat"],
    ),
    ...join(["ferie"], ["jobb", "vikar", "vikarar", "vikarer", "vikariat"]),
    ...join(["sesong"], ["hjelp", "jobb", "vikar", "vikarar", "vikarer", "vikariat"]),
    "summer",
]);

export const SOMMERJOBB_CATEGORIES = Object.freeze(
    [
        {
            label: "Butikk",
            values: [
                "butikk",
                "butikkarbeid",
                "butikkarbeider",
                "butikkmedarbeider",
                "butikkselger",
                "detaljhandel",
                "kiosk",
                "varepåfylling",
                "bensinstasjon",
            ],
        },
        {
            label: "Helse",
            values: [
                "ambulanse",
                "apotek",
                "apotektekniker",
                "barnehage",
                "barnehageassistent",
                "bpa",
                "eldreomsorg",
                "ergoterapeut",
                "farmasi",
                "farmasøyt",
                "fysioterapeut",
                "heimeteneste",
                "helse",
                "helsearbeid",
                "helsearbeider",
                "helsefag",
                "helsefagarbeider",
                "helsehjelp",
                "helsesekretær",
                "hjemmehjelp",
                "hjemmetjeneste",
                "hjemmetjenesten",
                "lege",
                "legesenter",
                "medisinstudent",
                "miljøarbeid",
                "miljøarbeider",
                "miljøterapeut",
                "miljøterapi",
                "omsorg",
                "omsorgsarbeid",
                "omsorgsbolig",
                "omsorgsbustad",
                "omsorgssenter",
                "sjukehus",
                "sykehjem",
                "sykehus",
                "sykehusapotek",
                "sykepleier",
                "sykepleierstudent",
                "tannhelse",
                "tannklinikk",
                "tannpleier",
            ],
        },
        {
            label: "Kontor",
            values: [
                "administrasjon",
                "analytiker",
                "arkiv",
                "arkivering",
                "dataanalyse",
                "databaser",
                "design",
                "hr",
                "informatikk",
                "kontor",
                "programmerer",
                "programmering",
                "prosjektmedarbeider",
                "saksbehandler",
                "saksbehandling",
                "sekretær",
                "strandsonekartlegger",
                "systemutvikler",
            ],
        },
        { label: "Kultur", values: ["kultur", "kunst", "musikk", "museum", "bibliotek"] },
        {
            label: "Kundeservice",
            values: [
                "billettering",
                "billettkontroll",
                "bilutleie",
                "booking",
                "feltsalg",
                "innsjekk",
                "innsjekking",
                "kundebehandler",
                "kundebehandling",
                "kontorbeplantning",
                "kundekonsulent",
                "kundekontakt",
                "kundesenter",
                "passasjerservice",
                "publikumsmottak",
                "resepsjon",
                "resepsjonist",
                "servicearbeid",
                "servicemedarbeider",
                "support",
                "telefonarbeid",
                "vakthold",
                "vekter",
                "fundraiser",
                "verver",
            ],
        },
        {
            label: "Lager og industri",
            values: [
                "anlegg",
                "anleggsarbeid",
                "bilverksted",
                "dekkbytte",
                "dekkhotell",
                "dekkmontering",
                "dekkomlegging",
                "drift",
                "fabrikk",
                "flyarbeider",
                "havbruk",
                "industri",
                "industriarbeider",
                "industrimekanikk",
                "lager",
                "lagerarbeid",
                "lageroperatør",
                "logistikk",
                "produksjon",
                "produksjonsarbeider",
                "produksjonsmedarbeider",
                "produktutvikling",
            ],
        },
        {
            label: "Renhold",
            values: [
                "housekeeper",
                "reinhald",
                "reinhold",
                "rengjøring",
                "renhold",
                "renholder",
                "renholdsarbeider",
                "renholdsmedarbeider",
                "vaskehjelp",
            ],
        },
        {
            label: "Restaurant og kafé",
            values: [
                "baker",
                "bakeri",
                "barista",
                "bartender",
                "cafe",
                "café",
                "foodtruck",
                "kafe",
                "kaffebar",
                "kafé",
                "kafémedarbeider",
                "kantine",
                "kjøkken",
                "kjøkkenassistent",
                "kjøkkenhjelp",
                "kjøkkenpersonell",
                "kokk",
                "restaurant",
                "ryddehjelp",
                "servering",
                "servitør",
                "storkjøkken",
            ],
        },
        {
            label: "Transport",
            values: ["avislevering", "isbil", "pakkelevering", "transport", "sjåfør", "kaptein"],
        },
        {
            label: "Turisme",
            values: ["turisme", "reiseliv", "guide", "guiding", "camping", "turistinformasjon", "turistvert"],
        },
        {
            label: "Utendørs",
            values: [
                "aktivitetsleder",
                "barnehage",
                "barnehageassistent",
                "festival",
                "festivalarbeid",
                "friluft",
                "friluftsbad",
                "gartner",
                "gjenvinning",
                "gravplass",
                "gressklipping",
                "grøntanlegg",
                "gårdsarbeid",
                "kirkegård",
                "landbruk",
                "miljøstasjon",
                "park",
                "parkanlegg",
                "parkarbeid",
                "parkarbeider",
                "parvedlikehold",
                "plenklipping",
                "renovasjon",
                "skog",
                "skogbruk",
                "stirydding",
                "turguide",
                "utearbeid",
                "utemiljø",
                "utendørs",
                "utendørsaktiviteter",
                "utendørsarbeid",
            ],
        },
    ].map((row) => Object.freeze({ label: row.label, values: Object.freeze(row.values) })),
);
