apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-stillingsok
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 3
    max: 4
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: /stillinger/internal/metrics
  liveness:
    initialDelay: 10
    path: /stillinger/internal/isAlive
  readiness:
    initialDelay: 10
    path: /stillinger/internal/isReady
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: false
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  env:
    - name: LOGINSERVICE_URL
      value: {{ loginservice_url }}
    - name: LOGOUTSERVICE_URL
      value: {{ logoutservice_url }}
    - name: PAMADUSER_URL
      value: {{ pamaduser_url }}
    - name: PAM_STILLINGSOK_URL
      value: {{ pam_stillingsok_url }}
    - name: PAM_VAR_SIDE_URL
      value: {{ pam_var_side_url }}
    - name: PAMSEARCHAPI_URL
      value: {{ pamsearchapi_url }}
    - name: AMPLITUDE_TOKEN
      value: {{ amplitude_token }}
    - name: UNLEASH_URL
      value: {{ unleash_url }}
    - name: NY_CV_URL
      value: {{ ny_cv_url }}
  accessPolicy:
    outbound:
      external:
        - host: unleash.nais.io
      rules:
        - application: pam-search-api
