apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: "stillingsok-alerts"
  namespace: "teampam"
  labels:
    team: "teampam"
spec:
  groups:
  - name: "teampam stillingsok alerts"
    rules:
    - alert: "[pam-stillingsok] Mye feil i loggene"
      expr: (100 * sum(rate(log_messages_errors{app="pam-stillingsok"}[3m])) / sum(rate(log_messages_total{app="pam-stillingsok"}[3m]))) > 1
      for: 3m
      annotations:
        action: "Sjekk loggene til pam-stillingsok i teampam for å se hvorfor det er så mye feil"
      labels:
        namespace: "teampam"
        severity: warning

    - alert: "[pam-stillingsok] Høy andel HTTP serverfeil (5xx responser)"
      expr: (100 * (sum by (service) (rate(nginx_ingress_controller_requests{status=~"5.*", status!~"503", namespace="teampam", service="pam-stillingsok"}[3m])) / sum by (service) (rate(nginx_ingress_controller_requests{namespace="teampam", service="pam-stillingsok"}[3m])))) > 1
      for: 3m
      annotations:
        action: "Sjekk loggene for å se hvorfor {{ $labels.service }} returnerer HTTP feilresponser"
      labels:
        namespace: "teampam"
        severity: critical

    - alert: "[pam-stillingsok] Høy andel HTTP serverfeil (503 responser), er søket nede eller er det bare scraping?"
      expr: sum(rate(nginx_ingress_controller_requests{host="arbeidsplassen.nav.no", path="/stillinger(/.*)?", status=~"503"}[5m])) > 12
      for: 10m
      annotations:
        action: "Sjekk loggene for å se hvorfor {{ $labels.service }} returnerer HTTP feilresponser"
      labels:
        namespace: "teampam"
        severity: critical

    - alert: "[pam-stillingsok] OpenSearch virker treg (over 750 ms gjennomsnittlig responstid)"
      expr: avg(rate(elastic_search_duration_seconds_sum{app="pam-stillingsok"}[1m])) > 0.75
      for: 10m
      annotations:
        action: "Sjekk loggene for å se hvorfor søket er tregt"
      labels:
        namespace: "teampam"
        severity: warning

    - alert: "[pam-stillingsok] OpenSearch suggestions virker treg (over 300 ms gjennomsnittlig responstid)"
      expr: avg(rate(suggestion_duration_seconds_sum{app="pam-stillingsok"}[3m])) > 0.3
      for: 10m
      annotations:
        action: "Sjekk loggene for å se hvorfor søkforslag er tregt"
      labels:
        namespace: "teampam"
        severity: warning

    - alert: "[pam-stillingsok] Ingen kall til OpenSearch på lang tid, er søket nede?"
      expr: sum(rate(elastic_search_requests{app="pam-stillingsok"}[3m])) == 0
      for: 10m
      annotations:
        action: "Sjekk loggene for å se om det er noe feil "
      labels:
        namespace: "teampam"
        severity: critical

    - alert: "[pam-stillingsok] Kall til pam-aduser feiler"
      expr: (100 * (sum(rate(aduser_requests{app="pam-stillingsok", result="failure"}[3m]))) / (sum(rate(aduser_requests{app="pam-stillingsok"}[3m])))) > 5
      for: 3m
      annotations:
        action: "Sjekk loggene for å se hvorfor så mange kall til pam-aduser feiler"
      labels:
        namespace: "teampam"
        severity: critical

    - alert: "[pam-stillingsok] Kall til OpenSearch feiler"
      expr: (100 * (sum(rate(elastic_search_requests{app="pam-stillingsok", result="failure"}[3m]))) / (sum(rate(elastic_search_requests{app="pam-stillingsok"}[3m])))) > 5
      for: 3m
      annotations:
        action: "Sjekk loggene for å se hvorfor så mange kall til OpenSearch feiler"
      labels:
        namespace: "teampam"
        severity: critical

    - alert: "[pam-stillingsok] Kall til OpenSearch suggestions feiler"
      expr: (100 * (sum(rate(suggestion_requests{app="pam-stillingsok", result="failure"}[3m]))) / (sum(rate(suggestion_requests{app="pam-stillingsok"}[3m])))) > 5
      for: 3m
      annotations:
        action: "Sjekk loggene for å se hvorfor så mange kall til OpenSearch suggestions feiler"
      labels:
        namespace: "teampam"
        severity: critical
