ingress:
  - "https://arbeidsplassen.intern.dev.nav.no"
arbeidsplassen_domain: "arbeidsplassen.intern.dev.nav.no"
env:
  ADUSER_AUDIENCE: "dev-gcp:teampam:pam-aduser"
  INTEREST_API_URL: "https://arbeidsplassen.intern.dev.nav.no/interesse-api",
  MULIGHETER_ENABLED: "true"
valkey:
  instance: stillingsok
  plan: startup-4
  project: nav-dev
  endpointId: f20f5b48-18f4-4e2a-8e5f-4ab3edb19733
openai_endpoint: "arbeidsmarked-dev.openai.azure.com"
