ingress:
  - "https://arbeidsplassen.intern.dev.nav.no/stillinger"
  - "https://arbeidsplassen.ekstern.dev.nav.no/stillinger/stilling"
  - "https://arbeidsplassen.ekstern.dev.nav.no/stillinger/js"
  - "https://arbeidsplassen.ekstern.dev.nav.no/stillinger/css"
  - "https://arbeidsplassen.ekstern.dev.nav.no/stillinger/images"
  - "https://arbeidsplassen.ekstern.dev.nav.no/stillinger/isAuthenticated"
  - "https://arbeidsplassen.ekstern.dev.nav.no/stillinger/api"
  - "https://arbeidsplassen.ekstern.dev.nav.no/stillinger/_next"
arbeidsplassen_domain: "arbeidsplassen.intern.dev.nav.no"
env:
  ADUSER_AUDIENCE: "dev-gcp:teampam:pam-aduser"
  AMPLITUDE_TOKEN: "3acd3a52e065d2d99856a12e7e9e1432"
  ASSET_PREFIX: "https://cdn.nav.no/teampam/pam-stillingsok"
  INTEREST_API_URL: "https://arbeidsplassen.intern.dev.nav.no/interesse-api"
  REDIS_AVAILABLE: "true"