ingress:
  - "https://arbeidsplassen.intern.dev.nav.no/stillinger"
  - "https://arbeidsplassen.ekstern.dev.nav.no/stillinger/stilling"
  - "https://arbeidsplassen.intern.dev.nav.no/sommerjobb"
arbeidsplassen_domain: "arbeidsplassen.intern.dev.nav.no"
env:
  ADUSER_AUDIENCE: "dev-gcp:teampam:pam-aduser"
  INTEREST_API_URL: "https://arbeidsplassen.intern.dev.nav.no/interesse-api"
redis:
  instance: stillingsok
  plan: startup-4
  project: nav-dev
  endpointId: f20f5b48-18f4-4e2a-8e5f-4ab3edb19733