ingress:
  - "https://arbeidsplassen.intern.dev.nav.no/stillinger"
  - "https://arbeidsplassen.ekstern.dev.nav.no/stillinger/stilling"
arbeidsplassen_domain: "arbeidsplassen.intern.dev.nav.no"
env:
  ADUSER_AUDIENCE: "dev-gcp:teampam:pam-aduser"
  AMPLITUDE_TOKEN: "3acd3a52e065d2d99856a12e7e9e1432"
  INTEREST_API_URL: "https://arbeidsplassen.intern.dev.nav.no/interesse-api"