apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-stillingsok
  namespace: teampam
  labels:
    team: teampam
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 3
    max: 4
    cpuThresholdPercentage: 50
  liveness:
    initialDelay: 10
    path: /stillinger/api/internal/isAlive
  readiness:
    initialDelay: 10
    path: /stillinger/api/internal/isReady
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 512Mi
  vault:
    enabled: false
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  env:
    - name: ADUSER_AUDIENCE
      value: {{ aduser_audience }}
    - name: AMPLITUDE_TOKEN
      value: {{ amplitude_token }}
    - name: INTEREST_API_URL
      value: {{ interest_api_url }}
    - name: PORT
      value: "8080"
    - name: REDIS_AVAILABLE
      value: "true"
  accessPolicy:
    inbound:
      rules:
        - application: pam-aduser
    outbound:
      rules:
        - application: pam-search-api
        - application: pam-aduser
      external:
        - host: {{ arbeidsplassen_domain }}
        - host: amplitude.nav.no
        - host: sentry.gc.nav.no
  redis:
    - instance: cache
      access: readwrite