apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-stillingsok
  namespace: teampam
  labels:
    team: teampam
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  image: {{ image }}
  port: 3000
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  liveness:
    initialDelay: 10
    path: /stillinger/api/internal/isAlive
  readiness:
    initialDelay: 10
    path: /stillinger/api/internal/isReady
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 750m
      memory: 256Mi
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
  vault:
    enabled: false
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: pam-aduser
    outbound:
      rules:
        - application: pam-search-api
        - application: pam-aduser
      external:
        - host: {{ arbeidsplassen_domain }}
        - host: amplitude.nav.no
        - host: sentry.gc.nav.no
  redis:
    - instance: cache
      access: readwrite