apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-stillingsok
  namespace: teampam
  labels:
    team: teampam
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/limit-connections: "5"
    nginx.ingress.kubernetes.io/limit-rps: "5"
    nginx.ingress.kubernetes.io/limit-rpm: "50"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
    nginx.ingress.kubernetes.io/denylist-source-range: "13.51.165.182,52.57.207.129,77.40.236.144,84.212.181.16,142.93.231.208,107.182.224.0/20,209.95.32.0/19,173.244.192.0/19,67.212.224.0/20"
spec:
  image: {{ image }}
  port: 3000
  replicas:
    min: 2
    max: 6
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  liveness:
    initialDelay: 10
    path: /api/internal/isAlive
  readiness:
    initialDelay: 10
    path: /api/internal/isReady
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 2048Mi
  prometheus:
    enabled: true
    path: /api/internal/prometheus
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  vault:
    enabled: false
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: pam-aduser
    outbound:
      rules:
        - application: search-api
          namespace: arbeidsplassen
        - application: pam-aduser
        - application: pam-geografi
      external:
        - host: {{ arbeidsplassen_domain }}
        - host: umami.nav.no
        - host: sentry.gc.nav.no
        - host: cdn.nav.no
  valkey:
    - instance: {{ valkey.instance }}
      access: readwrite
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
      
