apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-stillingsok
  namespace: teampam
  labels:
    team: teampam
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/limit-connections: "5"
    nginx.ingress.kubernetes.io/limit-rps: "5"
    nginx.ingress.kubernetes.io/limit-rpm: "50"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
    nginx.ingress.kubernetes.io/denylist-source-range: "13.51.165.182,52.57.207.129,77.40.236.144,84.212.181.16,142.93.231.208"
spec:
  image: {{ image }}
  port: 3000
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 60
  liveness:
    initialDelay: 10
    path: /stillinger/api/internal/isAlive
  readiness:
    initialDelay: 10
    path: /stillinger/api/internal/isReady
  resources:
    requests:
      cpu: 1000m
      memory: 512Mi
    limits:
      memory: 2048Mi
  prometheus:
    enabled: true
    path: /stillinger/api/internal/prometheus
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  vault:
    enabled: false
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
  envFrom:
    - secret: pam-ai
  accessPolicy:
    inbound:
      rules:
        - application: pam-aduser
    outbound:
      rules:
        - application: pam-search-api
        - application: pam-aduser
        - application: pam-geografi
      external:
        - host: {{ arbeidsplassen_domain }}
        - host: amplitude.nav.no
        - host: sentry.gc.nav.no
        - host: ai-stillingsok-poc.search.windows.net
  redis:
    - instance: {{ redis.instance }}
      access: readwrite