apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-stillingsok
  namespace: teampam
  labels:
    team: teampam
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "65532"
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 3
    max: 4
    cpuThresholdPercentage: 50
  liveness:
    initialDelay: 10
    path: /stillinger/api/internal/isAlive
  readiness:
    initialDelay: 10
    path: /stillinger/api/internal/isReady
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: false
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  env:
    - name: PORT
      value: "8080"
    - name: PAMADUSER_URL
      value: {{ pamaduser_url }}
    - name: INTEREST_API_URL
      value: {{ interest_api_url }}
    - name: PAM_STILLINGSOK_URL
      value: {{ pam_stillingsok_url }}
    - name: PAM_VAR_SIDE_URL
      value: {{ pam_var_side_url }}
    - name: PAMSEARCHAPI_URL
      value: {{ pamsearchapi_url }}
    - name: PAM_JOBBTREFF_API_URL
      value: {{ pam_jobbtreff_api_url }}
    - name: AMPLITUDE_TOKEN
      value: {{ amplitude_token }}
    - name: ARBEIDSPLASSEN_URL
      value: {{ arbeidsplassen_url }}
    - name: ADUSER_AUDIENCE
      value: {{ aduser_audience }}
    - name: IDPORTEN_AUDIENCE
      value: {{ idporten_audience }}
    - name: SENTRY_DSN
      value: {{ sentry_dsn }}
  accessPolicy:
    inbound:
      rules:
        - application: pam-aduser
    outbound:
      rules:
        - application: pam-search-api
        - application: pam-aduser
