ingress:
  - "https://arbeidsplassen.nav.no/stillinger"
arbeidsplassen_domain: "arbeidsplassen.nav.no"
env:
  ADUSER_AUDIENCE: "prod-gcp:teampam:pam-aduser"
  AMPLITUDE_TOKEN: "a7b3f00008ae250a08c3ebbc6bf718f9"
  INTEREST_API_URL: "https://arbeidsplassen.nav.no/interesse-api"
redis:
  instance: stillingsok
  plan: business-8
  project: nav-prod