ingress:
  - "https://arbeidsplassen.nav.no/stillinger"
arbeidsplassen_domain: "arbeidsplassen.nav.no"
env:
  ADUSER_AUDIENCE: "prod-gcp:teampam:pam-aduser"
  INTEREST_API_URL: "https://arbeidsplassen.nav.no/interesse-api"
valkey:
  instance: stillingsok
  plan: business-8
  project: nav-prod
  endpointId: 76685598-1048-4f56-b34a-9769ef747a92