apiVersion: aiven.io/v1alpha1
kind: Redis
metadata:
  labels:
    app: pam-stillingsok
    team: teampam
  name: redis-teampam-stillingsok
  namespace: teampam
spec:
  plan: startup-4
  project: nav-dev