apiVersion: aiven.io/v1alpha1
kind: Redis
metadata:
  labels:
    app: pam-stillingsok
    team: teampam
  name: redis-teampam-{{ redis.instance }}
  namespace: teampam
spec:
  plan: {{ redis.plan }}
  project: {{ redis.project }}
---
apiVersion: aiven.io/v1alpha1
kind: ServiceIntegration
metadata:
  labels:
    team: teampam
  name: redis-teampam-{{ redis.instance }}
  namespace: teampam
spec:
  project: {{ redis.project }}
  integrationType: prometheus
  destinationEndpointId: {{ redis.endpointId }}
  sourceServiceName: redis-teampam-{{ redis.instance }}