// This file is auto-generated by scripts/generate-skyra-csp-hashes.ts
// Do not edit manually.

export const SKYRA_INLINE_HASH_FALSE = "enyWhasmIUgkLDmf3yAqBUbRCOR9NbjGdRFuYrc2ozI=" as const;
export const SKYRA_INLINE_HASH_TRUE = "RW564V1IuRWP6loEkkMZLLNMpdOjWiFGpExcX86ueYA=" as const;
