const locations = [
    {
        key: "NORDLAND",
        m: [
            "BINDAL",
            "BODØ",
            "VÆRØY",
            "RØST",
            "GILDESKÅL",
            "BEIARN",
            "MELØY",
            "RØDØY",
            "FAUSKE",
            "SØRFOLD",
            "SALTDAL",
            "HAMARØY",
            "NARVIK",
            "STEIGEN",
            "VÅGAN",
            "HADSEL",
            "VESTVÅGØY",
            "FLAKSTAD",
            "MOSKENES",
            "SORTLAND",
            "ØKSNES",
            "LØDINGEN",
            "BØ (NORDLAND)",
            "ANDØY",
            "EVENES",
            "RANA",
            "HEMNES",
            "VEFSN",
            "GRANE",
            "HATTFJELLDAL",
            "NESNA",
            "LURØY",
            "TRÆNA",
            "ALSTAHAUG",
            "DØNNA",
            "HERØY (NORDLAND)",
            "VEVELSTAD",
            "LEIRFJORD",
            "BRØNNØY",
            "SØMNA",
            "VEGA",
        ],
    },
    {
        key: "VESTLAND",
        m: [
            "BERGEN",
            "ØYGARDEN",
            "BJØRNAFJORDEN",
            "OSTERØY",
            "ASKØY",
            "AUSTEVOLL",
            "STORD",
            "FITJAR",
            "BØMLO",
            "KVINNHERAD",
            "SVEIO",
            "ETNE",
            "KVAM",
            "ULLENSVANG",
            "SAMNANGER",
            "TYSNES",
            "VOSS",
            "AURLAND",
            "ULVIK",
            "VAKSDAL",
            "MODALEN",
            "EIDFJORD",
            "ALVER",
            "AUSTRHEIM",
            "FEDJE",
            "GULEN",
            "HØYANGER",
            "MASFJORDEN",
            "KINN",
            "STAD",
            "BREMANGER",
            "STRYN",
            "SUNNFJORD",
            "GLOPPEN",
            "SOGNDAL",
            "LÆRDAL",
            "LUSTER",
            "ÅRDAL",
            "VIK",
            "SOLUND",
            "HYLLESTAD",
            "FJALER",
            "ASKVOLL",
        ],
    },
    {
        key: "OSLO",
        m: ["OSLO"],
    },
    {
        key: "KONTINENTALSOKKELEN",
        m: [],
    },
    {
        key: "AKERSHUS",
        m: [
            "BÆRUM",
            "ASKER",
            "NORDRE FOLLO",
            "ÅS",
            "FROGN",
            "NESODDEN",
            "LØRENSKOG",
            "LILLESTRØM",
            "NITTEDAL",
            "VESTBY",
            "ENEBAKK",
            "NES (AKERSHUS)",
            "AURSKOG-HØLAND",
            "RÆLINGEN",
            "GJERDRUM",
            "NANNESTAD",
            "ULLENSAKER",
            "EIDSVOLL",
            "HURDAL",
            "LUNNER",
            "JEVNAKER",
        ],
    },
    {
        key: "BUSKERUD",
        m: [
            "DRAMMEN",
            "ØVRE EIKER",
            "MODUM",
            "SIGDAL",
            "LIER",
            "RINGERIKE",
            "HOLE",
            "KRØDSHERAD",
            "FLÅ",
            "NESBYEN",
            "NORE OG UVDAL",
            "GOL",
            "HEMSEDAL",
            "ÅL",
            "HOL",
            "KONGSBERG",
            "FLESBERG",
            "ROLLAG",
        ],
    },
    {
        key: "TELEMARK",
        m: [
            "TINN",
            "HJARTDAL",
            "NOTODDEN",
            "SKIEN",
            "SILJAN",
            "DRANGEDAL",
            "KRAGERØ",
            "MIDT-TELEMARK",
            "SELJORD",
            "NOME",
            "KVITESEID",
            "NISSEDAL",
            "VINJE",
            "FYRESDAL",
            "TOKKE",
            "PORSGRUNN",
            "BAMBLE",
        ],
    },
    {
        key: "INNLANDET",
        m: [
            "SØR-ODAL",
            "NORD-ODAL",
            "KONGSVINGER",
            "EIDSKOG",
            "GRUE",
            "ÅSNES",
            "HAMAR",
            "STANGE",
            "RINGSAKER",
            "LØTEN",
            "ELVERUM",
            "TRYSIL",
            "VÅLER (INNLANDET)",
            "ENGERDAL",
            "ÅMOT",
            "STOR-ELVDAL",
            "RENDALEN",
            "TYNSET",
            "TOLGA",
            "OS (INNLANDET)",
            "ALVDAL",
            "FOLLDAL",
            "LILLEHAMMER",
            "RINGEBU",
            "ØYER",
            "NORD-FRON",
            "SØR-FRON",
            "GAUSDAL",
            "DOVRE",
            "LESJA",
            "SEL",
            "VÅGÅ",
            "LOM",
            "SKJÅK",
            "GRAN",
            "GJØVIK",
            "ØSTRE TOTEN",
            "VESTRE TOTEN",
            "SØNDRE LAND",
            "NORDRE LAND",
            "ETNEDAL",
            "NORD-AURDAL",
            "SØR-AURDAL",
            "ØYSTRE SLIDRE",
            "VESTRE SLIDRE",
            "VANG",
        ],
    },
    {
        key: "FINNMARK",
        m: [
            "LOPPA",
            "ALTA",
            "GUOVDAGEAIDNU KAUTOKEINO",
            "HASVIK",
            "HAMMERFEST",
            "MÅSØY",
            "PORSANGER PORSÁNGU PORSANKI",
            "LEBESBY",
            "KARASJOHKA KARASJOK",
            "NORDKAPP",
            "GAMVIK",
            "VADSØ",
            "UNJARGGA NESSEBY",
            "DEATNU TANA",
            "SØR-VARANGER",
            "VARDØ",
            "BERLEVÅG",
            "BÅTSFJORD",
        ],
    },
    {
        key: "ROGALAND",
        m: [
            "STAVANGER",
            "SOLA",
            "RANDABERG",
            "STRAND",
            "SANDNES",
            "HJELMELAND",
            "KVITSØY",
            "SULDAL",
            "SAUDA",
            "KARMØY",
            "GJESDAL",
            "TIME",
            "KLEPP",
            "HÅ",
            "EIGERSUND",
            "SOKNDAL",
            "BJERKREIM",
            "LUND",
            "HAUGESUND",
            "UTSIRA",
            "TYSVÆR",
            "BOKN",
            "VINDAFJORD",
        ],
    },
    {
        key: "MØRE OG ROMSDAL",
        m: [
            "ÅLESUND",
            "SULA",
            "GISKE",
            "HAREID",
            "ULSTEIN",
            "HERØY (MØRE OG ROMSDAL)",
            "SANDE (MØRE OG ROMSDAL)",
            "VOLDA",
            "VANYLVEN",
            "ØRSTA",
            "STRANDA",
            "FJORD",
            "SYKKYLVEN",
            "HARAM",
            "AUKRA",
            "RAUMA",
            "MOLDE",
            "VESTNES",
            "HUSTADVIKA",
            "KRISTIANSUND",
            "AVERØY",
            "SMØLA",
            "AURE",
            "SUNNDAL",
            "TINGVOLL",
            "GJEMNES",
            "SURNADAL",
        ],
    },
    {
        key: "TROMS",
        m: [
            "KVÆFJORD",
            "TROMSØ",
            "BALSFJORD",
            "STORFJORD",
            "LYNGEN",
            "KARLSØY",
            "GÁIVUOTNA KÅFJORD",
            "NORDREISA",
            "KVÆNANGEN",
            "SKJERVØY",
            "SENJA",
            "SØRREISA",
            "DYRØY",
            "MÅLSELV",
            "SALANGEN",
            "LAVANGEN",
            "BARDU",
            "HARSTAD",
            "TJELDSUND",
            "IBESTAD",
            "GRATANGEN",
        ],
    },
    {
        key: "TRØNDELAG",
        m: [
            "RINDAL",
            "HEIM",
            "TRONDHEIM",
            "INDRE FOSEN",
            "ØRLAND",
            "ORKLAND",
            "ÅFJORD",
            "MELHUS",
            "HITRA",
            "FRØYA",
            "MIDTRE GAULDAL",
            "OPPDAL",
            "SKAUN",
            "RØROS",
            "HOLTÅLEN",
            "RENNEBU",
            "STJØRDAL",
            "MERÅKER",
            "MALVIK",
            "SELBU",
            "TYDAL",
            "LEVANGER",
            "FROSTA",
            "VERDAL",
            "INDERØY",
            "STEINKJER",
            "OSEN",
            "FLATANGER",
            "NAMSOS",
            "SNÅSA",
            "OVERHALLA",
            "GRONG",
            "HØYLANDET",
            "LIERNE",
            "NAMSSKOGAN",
            "RØYRVIK",
            "NÆRØYSUND",
            "LEKA",
        ],
    },
    {
        key: "SVALBARD",
        m: ["SVALBARD"],
    },
    {
        key: "JAN MAYEN",
        m: ["JAN MAYEN"],
    },
    {
        key: "ØSTFOLD",
        m: [
            "MOSS",
            "VÅLER (ØSTFOLD)",
            "FREDRIKSTAD",
            "RÅDE",
            "HVALER",
            "SARPSBORG",
            "HALDEN",
            "AREMARK",
            "INDRE ØSTFOLD",
            "SKIPTVET",
            "MARKER",
            "RAKKESTAD",
        ],
    },
    {
        key: "AGDER",
        m: [
            "FLEKKEFJORD",
            "SIRDAL",
            "KVINESDAL",
            "LINDESNES",
            "LYNGDAL",
            "ÅSERAL",
            "FARSUND",
            "HÆGEBOSTAD",
            "KRISTIANSAND",
            "VENNESLA",
            "IVELAND",
            "EVJE OG HORNNES",
            "BYGLAND",
            "VALLE",
            "BYKLE",
            "BIRKENES",
            "LILLESAND",
            "ARENDAL",
            "FROLAND",
            "ÅMLI",
            "GRIMSTAD",
            "TVEDESTRAND",
            "RISØR",
            "GJERSTAD",
            "VEGÅRSHEI",
        ],
    },
    {
        key: "VESTFOLD",
        m: ["HOLMESTRAND", "TØNSBERG", "FÆRDER", "SANDEFJORD", "HORTEN", "LARVIK"],
    },
    {
        key: "UTLAND",
        m: [],
    },
];

export default locations;
