export default function buildSourceIncludes() {
    return {
        includes: [
            "employer.name",
            "businessName",
            "properties.adtextFormat",
            "properties.employer",
            "properties.jobtitle",
            "properties.location",
            "properties.applicationdue",
            "properties.hasInterestform",
            "properties.needDriversLicense",
            "properties.under18",
            "properties.experience",
            "properties.education",
            "properties.workLanguage",
            "properties.remote",
            "locationList.postalCode",
            "locationList.city",
            "locationList.address",
            "locationList.municipal",
            "locationList.county",
            "locationList.country",
            "title",
            "published",
            "expires",
            "uuid",
            "status",
            "source",
            "medium",
            "reference",
            "categoryList.name",
            "categoryList.categoryType",
            "properties.keywords",
            "properties.searchtagsai",
            "properties.searchtags.label",
            "properties.searchtags.score",
            "occupationList.level1",
            "occupationList.level2",
            /* For debugging under 18 */
            "under18_facet",
            "generatedSearchMetadata.isUnder18",
            "generatedSearchMetadata.isUnder18Reason",
            "generatedSearchMetadata.shortSummary",
        ],
    };
}
