import { writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";

import { createSkyraInlineConfig } from "../src/app/_common/skyra/skyraConfig";
import { skyraOrg } from "../src/app/_common/skyra/skyraRuntime";

type SkyraHashes = Readonly<{
    consentFalse: string;
    consentTrue: string;
}>;

const sha256Base64 = (content: string): string => {
    return createHash("sha256").update(content, "utf8").digest("base64");
};

const generateHashes = (): SkyraHashes => {
    const inlineFalse = createSkyraInlineConfig({ org: skyraOrg, cookieConsent: false });
    const inlineTrue = createSkyraInlineConfig({ org: skyraOrg, cookieConsent: true });

    return {
        consentFalse: sha256Base64(inlineFalse),
        consentTrue: sha256Base64(inlineTrue),
    };
};

const createOutput = (hashes: SkyraHashes): string => {
    return (
        "// This file is auto-generated by scripts/generate-skyra-csp-hashes.ts\n" +
        "// Do not edit manually.\n" +
        "\n" +
        `export const SKYRA_INLINE_HASH_FALSE = "${hashes.consentFalse}" as const;\n` +
        `export const SKYRA_INLINE_HASH_TRUE = "${hashes.consentTrue}" as const;\n`
    );
};

const run = async (): Promise<void> => {
    const hashes = generateHashes();

    const outFile = path.join(process.cwd(), "src/app/_common/skyra/skyraCspHashes.generated.ts");

    await writeFile(outFile, createOutput(hashes), { encoding: "utf8" });
};

run().catch((error: unknown) => {
    console.error(error);
    process.exit(1);
});
