#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Sjekk om CI-miljøvariabelen er satt
if [ "$CI" = "true" ]; then
  echo "CI-miljø oppdaget, hopper over pre-push tester"
  exit 0
fi

npm run test