name: deploy-prod
on:
  release:
    types: [published]

jobs:
  call-workflow:
    permissions:
      contents: write
      id-token: write
    uses: navikt/pam-deploy/.github/workflows/deploy-prod.yml@v7
    with:
      NAIS_RESOURCE: .nais/nais.yml
      NAIS_VARS: .nais/prod.yml
  deploy-valkey:
    name: Deploy valkey
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy Valkey
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/valkey.yml
          VARS: .nais/prod.yml