name: build-deploy-dev
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
    branches:
      - 'master'
      - feature/*
jobs:
  call-workflow:
    uses: navikt/pam-deploy/.github/workflows/deploy-dev.yml@v2
    with:
      NODE_VERSION: 14
      BUILD_CACHE: npm
      LANGUAGE: node
      NAIS_RESOURCE: naiserator.yml
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      OPTIONAL_SECRET: ${{ secrets.READER_TOKEN }}
