name: build-deploy-feature
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - feature/*
jobs:
  build-and-deploy:
    uses: navikt/pam-deploy/.github/workflows/deploy-feature-branch.yml@v3
    with:
      LANGUAGE: "node"
      NODE_VERSION: "14"
      BUILD_CACHE: "npm"
      NAIS_RESOURCE: naiserator.yml
      NAIS_VARS: naiserator-dev.json
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      OPTIONAL_SECRET: ${{ secrets.READER_TOKEN }}
