name: build-deploy-dev
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.github/workflows/alerts.yml'
      - '.nais/alerts.yml'
    branches:
      - '**'
jobs:
  call-workflow:
    if: "(github.ref_name == 'master') || contains(github.event.head_commit.message, 'deploy:dev') || contains(github.ref, 'feature/')"
    uses: navikt/pam-deploy/.github/workflows/deploy-next-js-dev.yml@v7
    permissions:
      actions: read
      contents: write
      id-token: write
      packages: write
      security-events: write

    secrets: inherit
    with:
      SKIP_DRAFT_RELEASE: ${{ github.ref_name != 'master' }}
  deploy-valkey:
    name: Deploy valkey
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy Valkey
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/valkey.yml
          VARS: .nais/dev.yml
  e2e:
    name: Run E2E tests (${{ github.ref_name }})
    needs: call-workflow
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate UUID
        id: uuid
        shell: bash
        run: echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT

      - name: Set image tag from call-workflow output
        id: set-image
        run: echo "image=${{ needs.call-workflow.outputs.image }}" >> $GITHUB_OUTPUT

      - name: Run E2E tests
        env:
          cluster: dev-gcp
          var: jobid=${{ steps.uuid.outputs.uuid }},image=${{ steps.set-image.outputs.image }}
          team: teampam
          resource: .nais/e2e-job.yml
          image: ${{ steps.set-image.outputs.image }}