name: build-deploy-feature
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - feature/*
jobs:
  build-and-deploy:
    uses: navikt/pam-deploy/.github/workflows/deploy-feature-branch.yml@v4
    permissions:
      actions: read
      contents: write
      id-token: write
      packages: write
      security-events: write
    with:
      LANGUAGE: "node"
      NODE_VERSION: "14"
      BUILD_CACHE: "npm"
      NAIS_RESOURCE: .nais/nais.yml
      NAIS_VARS: .nais/dev.json
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      OPTIONAL_SECRET: ${{ secrets.READER_TOKEN }}
