name: build-deploy-dev
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
    branches:
      - '**'

jobs:
  call-workflow:
    if: "(github.ref_name == 'master') || contains(github.event.head_commit.message, 'deploy:dev') || contains(github.ref, 'feature/')"
    uses: navikt/pam-deploy/.github/workflows/deploy-dev.yml@v7
    permissions:
      actions: read
      contents: write
      id-token: write
      packages: write
      security-events: write
    with:
      LANGUAGE: ""
      BUILD_SCRIPT: ""
      NAIS_RESOURCE: .nais/nais.yml
      NAIS_VARS: .nais/dev.json
      SKIP_DRAFT_RELEASE: ${{ github.ref_name != 'master' }}
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      OPTIONAL_SECRET: ${{ secrets.READER_TOKEN }}
