name: build-deploy-feature
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - feature/*
jobs:
  build-and-deploy:
    uses: navikt/pam-deploy/.github/workflows/deploy-feature-branch.yml@v3
    with:
      LANGUAGE: "node"
      NODE_VERSION: "14"
      BUILD_CACHE: "npm"
      NAIS_RESOURCE: naiserator.yml
      NAIS_VARS: naiserator-dev.yml
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      OPTIONAL_SECRET: ${{ secrets.READER_TOKEN }}




#  build-and-deploy-feature:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '14'
#          cache: 'npm'
#      - name: build and test
#        run: |
#          npm install
#          npm run build
#      - name: build and push docker image
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          APPLICATION=$(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)
#          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)
#          VERSION_TAG=${GITHUB_REF##*/}-$SHORT_SHA
#          IMAGE=ghcr.io/$GITHUB_REPOSITORY:$VERSION_TAG
#          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
#          docker build . --pull -t $IMAGE
#          echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_REPOSITORY" --password-stdin ghcr.io
#          docker push $IMAGE
#      - name: deploy to dev-gcp
#        uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: dev-gcp
#          RESOURCE: naiserator.yml
#          VARS: naiserator-dev.json
