name: build-deploy-dev
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
    branches:
      - '**'

jobs:
  call-workflow:
    if: "(github.ref_name == 'master') || contains(github.event.head_commit.message, 'deploy:dev') || contains(github.ref, 'feature/')"
    uses: navikt/pam-deploy/.github/workflows/deploy-next-js-dev.yml@next-js-deploy
    permissions:
      actions: read
      contents: write
      id-token: write
      packages: write
      security-events: write
    secrets: inherit
    with:
      SKIP_DRAFT_RELEASE: ${{ github.ref_name != 'master' }}
